


--- export PGPASSWORD=<password>
--- psql -h <host> -d <database> -U <user_name> -p <port> -a -w -f <file>.sql


DROP TABLE IF EXISTS cmdb_core.position, cmdb_core.location;
DROP SCHEMA cmdb_core;

CREATE SCHEMA cmdb_core;


CREATE TABLE cmdb_core.location (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country         text NOT NULL,
    state           text NOT NULL,
    town            text NOT NULL,
    street          text NOT NULL,
    zipcode         text NOT NULL
);

CREATE TABLE cmdb_core.position (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building        INTEGER REFERENCES cmdb_core.location (id),
    floor           INTEGER NOT NULL,
    room            text NOT NULL,
    rack            text NOT NULL,
    rack_position   text NOT NULL
);

CREATE INDEX position_id_index ON cmdb_core.position (id);


---
--- COMPANY
---
CREATE TABLE cmdb_core.contact (
    id integer      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            text NOT NULL,
    phone           text NOT NULL,
    phone2          text NOT NULL,
    email           text NOT NULL,
    other           text NOT NULL
);

CREATE TABLE cmdb_core.corporation (
    id integer      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            text NOT NULL,
    tax_id          text NOT NULL,
    bank_acc        text NOT NULL,
    corp_address    INTEGER REFERENCES cmdb_core.location (id),
    corp_contact    INTEGER REFERENCES cmdb_core.contact (id),
    description     text NOT NULL
);

CREATE TABLE cmdb_core.department (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    corp_id         INTEGER REFERENCES cmdb_core.corporation (id),
    dept_contact    INTEGER REFERENCES cmdb_core.contact (id),
    dept_name       text NOT NULL,
    dept_description     text NOT NULL,
    responsible     text NOT NULL --- TODO : responsible person
);




---
--- HOST
---
CREATE TYPE host_type AS ENUM ('physical', 'virtual');

CREATE TABLE cmdb_core.host (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ip_addr         inet NOT NULL,
    mac_addr        macaddr NOT NULL,
    hostname        text NOT NULL,
    host_t          host_type NOT NULL,
    dns_hostname    text NOT NULL DEFAULT 'localhost.localdomain'
);

CREATE INDEX host_id_index ON cmdb_core.host (id);

CREATE TABLE cmdb_core.physical_host (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    building        INTEGER REFERENCES cmdb_core.position (id),
    host            INTEGER REFERENCES cmdb_core.host (id)
);
