












CREATE TABLE location (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country       varchar (40) NOT NULL,
    state         varchar (40) NOT NULL,
    town          varchar (40) NOT NULL,
    street        varchar (40) NOT NULL,
    zipcode       varchar (40) NOT NULL
);

CREATE TABLE position (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    location_id integer REFERENCES location (id),
    block       varchar (40) NOT NULL,
    floor         varchar (40) NOT NULL,
    room          varchar (40) NOT NULL,
    street        varchar (40) NOT NULL,
    rack       varchar (40) NOT NULL,
    rack_position      INTEGER NOT NULL
);

CREATE INDEX position_id_index ON position (id);